name: Fadah
api-version: 1.21
version: ${version}
main: info.preva1l.fadah.Fadah
load: POSTWORLD
author: Preva1l
website: https://docs.preva1l.info/
folia-supported: true
softdepend:
  - PlaceholderAPI
  - LuckPerms
  - mcMMO
  - Vault
  - RedisEconomy
  - CoinsEngine
  - PlayerPoints
  - EcoItems
  - zAuctionHouseV3
  - AuctionHouse
